---
- name: Configure Elk VM with Docker
  hosts: elk
  become: true
  tasks:

    - name: configure memory
      sysctl:
        name: vm.max_map_count
        value: '262144'
        sysctl_set: yes
        state: present
        reload: yes
    
    - name: install docker
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

    - name: install python dependencies
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: install docker SDK for Python
      pip:
        name: docker
        state: present
    
    - name: download and launch dockerized ELK container
      docker_container:
        name: elk
        image: sebp/elk
        state: started
        restart_policy: always
        published_ports:
          -  "5601:5601"
          -  "9200:9200"
          -  "5044:5044"

    - name: Enable service docker on boot
      systemd:
        name: docker
        daemon_reload: yes
        enabled: yes